# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYlQFTSHJSmsGP1inIA-GAe2oob5YN36
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Alternative to `drive.mount()`: Using `PyDrive`

If `drive.mount()` is not working or if you prefer to interact with Google Drive files programmatically rather than mounting it as a filesystem, you can use the `PyDrive` library. This allows you to authenticate and then list, upload, or download files directly.
"""

# Install the PyDrive library
!pip install -U -q PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate Colab user (this will open a new window for authentication if needed)
auth.authenticate_user()

# Create GoogleAuth instance.
gauth = GoogleAuth()

# Explicitly set 'embedded' to True to prevent PyDrive from attempting
# to launch a local webserver for authentication, which requires client_secrets.json.
# This forces PyDrive to use an authentication flow suitable for Colab.
gauth.embedded = True

# Explicitly set 'client_config_backend' in gauth's settings AFTER initialization
# as a defensive measure against other potential client config loads.
gauth.settings['client_config_backend'] = 'settings'

# Load the credentials obtained from google.colab.auth
gauth.credentials = GoogleCredentials.get_application_default()

# Create the PyDrive client using the gauth object
drive = GoogleDrive(gauth)

print('PyDrive client authenticated and ready.')

# Example: List files in your Google Drive root directory
# You can adjust the 'q' parameter to search for specific files/folders
file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()
for file in file_list:
  print('title: %s, id: %s' % (file['title'], file['id']))

print(f'\nFound {len(file_list)} files/folders in your Drive root.')

from google.colab import drive
drive.mount('/content/drive', force_remount=True)


from google.colab import files
uploaded = files.upload()


import pandas as pd
import io
df = pd.read_csv(io.BytesIO(list(uploaded.values())[0]))
print(df.shape)

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
df = pd.read_csv(io.BytesIO(list(uploaded.values())[0]))
print(df.shape)

print(df.columns)

# Q#1 Definitions

# 1. NumPy
print("1. NumPy:")
print("NumPy is a Python library used for numerical computations. It supports arrays, matrices, and mathematical functions.")
print()

# 2. Matplotlib
print("2. Matplotlib:")
print("Matplotlib is a Python library used for data visualization. It creates charts, graphs, and plots.")
print()

# 3. Pandas
print("3. Pandas:")
print("Pandas is a Python library used for data manipulation and analysis. It works with tables called DataFrames.")
print()

# 4. TensorFlow
print("4. TensorFlow:")
print("TensorFlow is a Python library by Google used for deep learning and building neural networks.")
print()

# 5. Seaborn
print("5. Seaborn:")
print("Seaborn is a Python library for statistical data visualization. It makes beautiful charts easily.")
print()

# 6. Sklearn
print("6. Sklearn (Scikit-learn):")
print("Sklearn is a Python library for machine learning. It has tools for classification, regression, and clustering.")

# Q#2 Dataset Analysis

# Number of features (columns)
print("Number of Features (columns):", df.shape[1])
print()

# Number of instances (rows)
print("Number of Instances (rows):", df.shape[0])
print()

# List at least 5 features
print("5 Features of Titanic Dataset:")
print("1.", df.columns[0])
print("2.", df.columns[1])
print("3.", df.columns[2])
print("4.", df.columns[3])
print("5.", df.columns[4])

# Dataset Information

print("1. Website Name of Dataset:")
print("   Kaggle - www.kaggle.com")
print()

print("2. Is Titanic a Benchmark Dataset?")
print("   YES! Titanic is a very famous Benchmark dataset.")
print("   It is used worldwide for learning Machine Learning.")
print()

print("3. Is data Structured or Unstructured?")
print("   STRUCTURED data - because it is in table format (rows and columns)")
print()

print("4. Check if any Text in cells:")
print(df.dtypes)

# ML Process Steps

print("Machine Learning Process:")
print()
print("1. Data Collection")
print("2. Data Preprocessing")
print("3. Exploratory Data Analysis (EDA)")
print("4. Feature Selection")
print("5. Model Selection")
print("6. Model Training")
print("7. Model Testing")
print("8. Model Evaluation")
print("9. Model Deployment")

# Prepare data for KNN Model
from sklearn.preprocessing import LabelEncoder

# Drop text columns that can't be used
df_model = df.drop(['Name', 'Ticket', 'Cabin'], axis=1)

# Fill missing values
df_model = df_model.fillna(df_model.mean(numeric_only=True))
df_model['Embarked'] = df_model['Embarked'].fillna('S')

# Convert text to numbers
le = LabelEncoder()
df_model['Sex'] = le.fit_transform(df_model['Sex'])
df_model['Embarked'] = le.fit_transform(df_model['Embarked'])

print("Data Prepared Successfully!")
print(df_model.shape)

# Train KNN Model
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Define X (features) and y (target)
X = df_model.drop('Survived', axis=1)
y = df_model['Survived']

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create KNN model
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn.fit(X_train, y_train)

print("KNN Model Trained Successfully!")
print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

# Testing and Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Test the model
y_pred = knn.predict(X_test)

# Training Result
train_score = knn.score(X_train, y_train)
print("Training Result:", round(train_score * 100, 2), "%")

# Testing Result
test_score = accuracy_score(y_test, y_pred)
print("Testing Result:", round(test_score * 100, 2), "%")
print()

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
print()

# Detailed Report
print("Classification Report:")
print(classification_report(y_test, y_pred))